name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the repo
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.email "arnavmaha2211@gmail.com"
          git config --global user.name "Arnav"

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add space https://user:$HF_TOKEN@huggingface.co/spaces/Arnav2211/Book-Recommender
          git push --force space main
